apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "apono-connector.fullname" . }}
  labels:
    {{- include "apono-connector.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "apono-connector.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        releaseTime: {{ dateInZone "2006-01-02 15:04:05Z" (now) "UTC"| quote }}
        {{ if .Values.podAnnotations }}
        {{ toYaml .Values.podAnnotations | nindent 8 }}
        {{ end }}
      labels:
        {{- include "apono-connector.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "apono-connector.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: git-sync
              readOnly: true
              mountPath: "/app/git-sync"
          env:
            - name: APONO_URL
              value: {{ .Values.apono.url }}
            - name: APONO_WEBSOCKET_SSL
              value: {{ .Values.apono.websocketSsl }}
            - name: APONO_ACTIONS_PARALLELISM
              value: {{ .Values.apono.actionsParallelism | quote }}
            - name: APONO_ACTIONS_QUEUE_SIZE
              value: {{ .Values.apono.actionsQueueSize | quote }}
            - name: APONO_TOKEN
              valueFrom:
                secretKeyRef:
                  name: apono
                  key: token
            - name: APONO_CONNECTOR_ID
              valueFrom:
                secretKeyRef:
                  name: apono-connector-id
                  key: id
            - name: TEMPLATES_PATH
              value: "/app/git-sync/apono-agent-templates"
        - name: git-sync
          image: {{ .Values.gitSyncImage | quote }}
          env:
            - name: GIT_SYNC_REPO
              value: "https://{{ .Values.githubAccessToken }}@github.com/{{ .Values.templatesRepository }}"
            - name: GIT_SYNC_BRANCH
              value: "master"
            - name: GIT_SYNC_WAIT
              value: "300"
          volumeMounts:
            - name: git-sync
              mountPath: "/tmp/git"

      volumes:
        - name: git-sync
          emptyDir: {}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
