apiVersion: v1
kind: Secret
metadata:
  name: apono-connector-id
  annotations:
    "helm.sh/resource-policy": "keep"
type: Opaque
data:
{{- if empty .Values.apono.connectorId }}
  # retrieve the secret data using lookup function and when not exists, return an empty dictionary / map as result
  {{- $secret := (lookup "v1" "Secret" .Release.Namespace "apono-connector-id") | default dict }}
  {{- if $secret }}
  id: {{ $secret.data.id }}
  {{- else}}
  id: {{ uuidv4 | b64enc | quote }}
  {{- end}}
{{- else }}
  id: {{ .Values.apono.connectorId | b64enc | quote }}
{{- end }}
