{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "apono-connector.serviceAccountName" . }}
  labels:
    {{- include "apono-connector.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount }}
  annotations:
{{/*    {{ toYaml .annotations | nindent 4 }}*/}}
    {{ if .awsRoleName }}
    "eks.amazonaws.com/role-arn": "arn:aws:iam::{{ .awsRoleAccountId }}:role/{{ .awsRoleName }}"
    {{- end }}
  {{- end }}
{{- end }}
